version: '3.7'
services:

  web:
    build: ./library
    restart: always
#    command: gunicorn -w 4 library:init
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./library/:/library
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=library

volumes:
  postgres_data: